
DROP DATABASE DB;
CREATE DATABASE DB;

-- connect to database DB

DROP TABLE T;
CREATE TABLE T (c VARCHAR(1), n INT);

INSERT INTO T VALUES ('A', 1);
INSERT INTO T VALUES ('A', 1);
INSERT INTO T VALUES ('D', 1);
INSERT INTO T VALUES ('E', 1);
INSERT INTO T VALUES ('F', 1);
INSERT INTO T VALUES ('G', 1);
INSERT INTO T VALUES ('H', 1);
INSERT INTO T VALUES ('A', 2);
INSERT INTO T VALUES ('B', 2);
INSERT INTO T VALUES ('C', 2);
INSERT INTO T VALUES ('D', 2);
INSERT INTO T VALUES ('E', 2);
INSERT INTO T VALUES ('F', 2);
INSERT INTO T VALUES ('G', 2);

SELECT * FROM T;
SELECT c, n FROM T;
SELECT DISTINCT c, n FROM T;
SELECT c, n FROM T;