-- CREATE TABLE people AS
-- (
-- SELECT nme, cty, addrs FROM childhoodpersons
-- UNION
-- SELECT nme, cty, addrs FROM persons FROM primaryschoolpersons
-- UNION
-- SELECT nme, cty, addrs FROM persons FROM highschoolpersons
-- UNION
-- SELECT nme, cty, addrs FROM persons FROM univeritypersons
-- )